"""
Django settings for gdeed project.

Generated by 'django-admin startproject' using Django 5.2.7.
Documentation:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-qe3x1vk3p*6i=g6fg3z)#7tb%pnlbtmfo9p%qy*hh)(^47n#+b'
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    'django.contrib.admin',  #
    'django.contrib.auth',  #
    'django.contrib.contenttypes',  #
    'django.contrib.sessions',  #
    'django.contrib.messages',  #
    'django.contrib.staticfiles',  #
 # Cloudinary
    'cloudinary_storage',
    'cloudinary',

    'core',        # الواجهة والصفحات العامة (SSR)
    'shop',        # المتجر – المنتجات والسلة والطلبات والدفع
    'accounts',    # الحسابات – المستخدمون ولوحة التحكم
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gdeed.urls'  # اسم التطبيق والمسار الخاص به

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gdeed.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',        # C:\Users\alamr\gdeed\static
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # C:\Users\alamr\gdeed\staticfiles

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'         # C:\Users\alamr\gdeed\media

LOCALE_PATHS = [BASE_DIR / 'locale']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name="اسم_السحابة_الخاص_بك",
    api_key="مفتاح_API_الخاص_بك",
    api_secret="الرمز_السري_الخاص_بك",
    secure=True
)

# استخدم Cloudinary كمخزن للوسائط (MEDIA)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
# ----------------------------------------
# ☁️ إعدادات Cloudinary لتخزين الوسائط
# ----------------------------------------
import cloudinary
import cloudinary.uploader
import cloudinary.api

# بيانات الاتصال من لوحة Cloudinary Dashboard
# ⚠️ ملاحظة: في بيئة الإنتاج يُفضل استخدام ملف .env لحماية المفاتيح
cloudinary.config(
    cloud_name="dkzbyddkp",                      # اسم السحابة (Cloud Name)
    api_key="815734787826891",                   # مفتاح API
    api_secret="8FcVRKkbVONyzmQYPGQl1hkJGvg",    # المفتاح السري (API Secret)
    secure=True                                  # استخدام HTTPS الآمن
)

# استخدم Cloudinary كمخزن افتراضي للوسائط (Media)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
