"""
Django settings for gdeed project.

Generated by 'django-admin startproject' using Django 5.2.7.
Documentation:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path

# ----------------------------------------
# 🧩 المسار الأساسي للمشروع
# ----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------
# 🔐 مفاتيح الأمان
# ----------------------------------------
SECRET_KEY = 'django-insecure-qe3x1vk3p*6i=g6fg3z)#7tb%pnlbtmfo9p%qy*hh)(^47n#+b'
DEBUG = True
ALLOWED_HOSTS = []

# ----------------------------------------
# 🧱 التطبيقات المثبتة
# ----------------------------------------
INSTALLED_APPS = [
    # تطبيقات Django الافتراضية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # تطبيقات المشروع الداخلية
    'core',        # الواجهة والصفحات العامة (SSR)
    'shop',        # المتجر – المنتجات والسلة والطلبات والدفع
    'accounts',    # الحسابات – المستخدمون ولوحة التحكم
]

# ----------------------------------------
# ⚙️ الميدل وير
# ----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ----------------------------------------
# 🌐 إعدادات المسارات العامة
# ----------------------------------------
ROOT_URLCONF = 'gdeed.urls'

# ----------------------------------------
# 🖥️ إعدادات القوالب (Templates)
# ----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # مسار القوالب العام: C:\Users\alamr\gdeed\templates
        'DIRS': [BASE_DIR / 'templates'],

        # تفعيل القوالب داخل كل تطبيق تلقائيًا (core, shop, accounts)
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ----------------------------------------
# 🧩 تطبيق WSGI
# ----------------------------------------
WSGI_APPLICATION = 'gdeed.wsgi.application'

# ----------------------------------------
# 🗄️ قاعدة البيانات
# ----------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ----------------------------------------
# 🔑 التحقق من كلمات المرور
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------
# 🌍 اللغة والتوقيت
# ----------------------------------------
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Asia/Riyadh'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ----------------------------------------
# 🖼️ إعدادات الملفات الثابتة (Static Files)
# ----------------------------------------
# عنوان الوصول عبر المتصفح
STATIC_URL = '/static/'

# مجلد التطوير الأساسي
STATICFILES_DIRS = [
    BASE_DIR / 'static',        # C:\Users\alamr\gdeed\static
]

# مجلد التجميع النهائي عند تنفيذ collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'  # C:\Users\alamr\gdeed\staticfiles

# ----------------------------------------
# 📁 إعدادات ملفات الوسائط (Media Files)
# ----------------------------------------
# عنوان الوصول عبر المتصفح
MEDIA_URL = '/media/'

# المجلد الفعلي لحفظ الملفات
MEDIA_ROOT = BASE_DIR / 'media'         # C:\Users\alamr\gdeed\media

# ----------------------------------------
# 🌐 إعدادات الترجمة (لللغات المتعددة)
# ----------------------------------------
LOCALE_PATHS = [BASE_DIR / 'locale']

# ----------------------------------------
# ⚙️ الإعداد الافتراضي لمعرف الجداول
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------
# ⚡ إعدادات إضافية مستقبلية للنشر
# ----------------------------------------
# يمكنك تفعيلها لاحقًا عند النشر على السيرفر:
# SECURE_SSL_REDIRECT = True
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
