"""
Django settings for gdeed project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# المسار الأساسي للمشروع
BASE_DIR = Path(__file__).resolve().parent.parent

# مفتاح الأمان (يُفضَّل لاحقًا وضعه في متغير بيئة)
SECRET_KEY = 'django-insecure-qe3x1vk3p*6i=g6fg3z)#7tb%pnlbtmfo9p%qy*hh)(^47n#+b'

# وضع التطوير
DEBUG = True

# النطاقات المسموح بها
ALLOWED_HOSTS = []

# -----------------------------
# 🔹 التطبيقات المثبتة
# -----------------------------
INSTALLED_APPS = [
    # تطبيقات Django الافتراضية
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # -----------------------------
    # 🔸 التطبيقات الداخلية للمشروع
    # -----------------------------
    'core',        # الواجهة والصفحات العامة (SSR)
    'shop',        # المتجر – المنتجات والسلة والطلبات والدفع
    'accounts',    # إدارة المستخدمين والصلاحيات ولوحة التحكم
]

# -----------------------------
# 🔹 ميدل وير
# -----------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    # تمكين تعدد اللغات (العربية / الإنجليزية)
    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -----------------------------
# 🔹 إعدادات المسارات
# -----------------------------
ROOT_URLCONF = 'gdeed.urls'

# -----------------------------
# 🔹 إعدادات القوالب (Templates)
# -----------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # مجلد القوالب العام
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -----------------------------
# 🔹 تطبيق WSGI
# -----------------------------
WSGI_APPLICATION = 'gdeed.wsgi.application'

# -----------------------------
# 🔹 قاعدة البيانات (SQLite)
# -----------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -----------------------------
# 🔹 التحقق من كلمات المرور
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -----------------------------
# 🔹 إعدادات اللغة والتوقيت
# -----------------------------
LANGUAGE_CODE = 'ar'             # اللغة العربية
TIME_ZONE = 'Asia/Riyadh'        # التوقيت المحلي للرياض
USE_I18N = True
USE_L10N = True
USE_TZ = True

# -----------------------------
# 🔹 الملفات الثابتة (Static Files)
# -----------------------------
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # مجلد الملفات الثابتة للمطور

# -----------------------------
# 🔹 الملفات المرفوعة (Media Files)
# -----------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------
# 🔹 إعدادات الترجمة
# -----------------------------
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# -----------------------------
# 🔹 الإعداد الافتراضي لمعرّفات الجداول
# -----------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
